### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by overthink** [Tom006k/Sortable-coding-challenge#1]
Hi there.

There are a couple of issues with your output format that are preventing me from checking your solutions results.

1) In the result file, each listing in the "listings" array needs to be the full listing object (title, manufacturer, currency, price)from the input file.  Right now you've just got "title" field.
2) Each result object should be on a single line in the output file -- right now they are pretty printed.

See http://sortable.com/challenge/ for details.

I'll take another look after these issues are resolved. Thanks!

Mark (from sortable.com)

**Comment by Tom006k** [comment]
Hi Mark,

I have corrected the issues. I apologise, I assumed you would not want duplicate information so did not include the full listing, instead thinking the title would be used as a reference to pull the information from the original listing file if needed. As for the single line for each object, I'm sorry to say it slipped my mind that that was a requirement.

The full listing information is now included in the array, and I have added the option to write the information as it was, or using a single line for each object, and selected the single line option for the implementation as required. Here is the URL again: https://github.com/Tom006k/Sortable-coding-challenge

Kind regards

Thomas Richards
